spring:
    application:
        name: service-order
    cloud:
        nacos:
            server-addr: 127.0.0.1:8848
            # config:
            #     namespace: dev # 读取什么命名空间
        openfeign: # 超时配置
            client: #客户端配置
                config:
                    server-product: #服务名字
                        logger-level: full
                        connect-timeout: 5000 #请求超时时间
                        read-timeout: 6000 #业务超时时间
                        # retryer: feign.retryer.Default # 重试机制
    config:
        import: nacos:service-order.yml #?group=groupName
server:
    port: 8000

# 设置loglevel
logging:
    level:
        com.example.order.service: debug
