spring:
    application:
        name: gateway
    cloud:
        nacos:
            server-addr: 127.0.0.1:8848
        gateway:
            routes:
            - id: order
              uri: lb://service-order
              predicates:
                    - Path=/api/order/**
            - id: product
              uri: lb://service-product
              predicates:
                - Path=/api/product/**
server:
    port: 80