spring:
    application:
        name: service-product
    cloud:
        sentinel:
            transport:
                dashboard: localhost:8080 # sentinel仪表盘
            eager: true
        nacos:
            config:
                import-check:
                    enabled: false #允许不写spring.config.import
            server-addr: 127.0.0.1:8848
server:
    port: 9000
